create table usuario (
    codigo bigint generated by default as identity,
    email  varchar(255),
    senha  varchar(255),
    primary key (codigo)
);

insert into usuario (codigo, email, senha)
values (1, 'danilo@gmail.com', '$2a$10$pr7W.k8hYTdlfRfw2l0EneK.Zv1V7hqIWebiiyfQ0Iq0lqKmJVc4e');

insert into usuario (codigo, email, senha)
values (2, 'carlos@gmail.com', '$2a$10$pr7W.k8hYTdlfRfw2l0EneK.Zv1V7hqIWebiiyfQ0Iq0lqKmJVc4e');

create table evento (
    codigo         bigint not null,
    data           timestamp,
    descricao      varchar(255),
    usuario_codigo bigint,
    primary key (codigo)
);

alter table evento
    add constraint fk_usuario foreign key (usuario_codigo) references usuario;

insert into evento (codigo, descricao, data, usuario_codigo)
values (1, 'Gravar Vídeos', current_timestamp, 1);

insert into evento (codigo, descricao, data, usuario_codigo)
values (2, 'Reunião sobre Novo Projeto', current_timestamp, 1);

insert into evento (codigo, descricao, data, usuario_codigo)
values (3, 'Ir ao Cinema', current_timestamp, 2);